    ;do $System.OBJ.LoadDir("/opt/irisbuild/src","ck",,1)

    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    zn "USER"
    zpm "install git-source-control"
    do ##class(%Studio.SourceControl.Interface).SourceControlClassSet("SourceControl.Git.Extension")
    zpm "install passwordless"
    zpm "install objectscript-json-trace-viewer"

    Set ^GPT.model = "gpt-3.5-turbo-0613"
    
    Set ^GPT.openAI.APIKeys = "<OpenAI.KEY>"

    Set ^GPT.engine("implementation") = "/home/irisowner/dev/prompt-implementation-engineer.txt"
    Set ^GPT.engine.initial("implementation") = "Write pyhton code"

    Set ^GPT.engine("rule") = "/home/irisowner/dev/prompt-rule-engineer.txt"
    Set ^GPT.engine.initial("rule") = "Write xml structure Of XDATA content:"


    zpm "load /home/irisowner/dev/ -dev -v":1:1
    halt
